[package]
name = "mile_db"
version = "0.1.0"
edition = "2024"

[dependencies]
redb = "1.5"
serde = { version = "1", features = ["derive"] }
bincode = "1"
parking_lot = "0.12"
blake3 = "1"
thiserror = "1"
